# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt     #  args: ["--enable require-variable-braces,deprecate-which"]
      - id: terraform_tflint
        args:
            - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
                     --disable-rule=terraform_required_version
                     --disable-rule=terraform_required_providers
      - id: terragrunt_fmt
      - id: terraform_docs
