# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "batcave-dev-us-east-1-tf-state"
    encrypt = true
    key     = "delete_ebs_volumes/./terraform.tfstate"
    region  = "us-east-1"
  }
}
