variable "iam_path" {}
variable "permissions_boundary" {}
variable "lambda_name" {}
variable "aws_region" {}
variable "environment" {}
variable "project" {}
variable "event_schedule_cron" {}
variable "log_retention" {}
variable "lambda_timeout" {}
