variable "iam_path" {}
variable "permissions_boundary" {}
variable "lambda_name" {}
variable "aws_region" {}
variable "environment" {}
variable "directory_name" {}
variable "account" {}
variable "project" {}
variable "owner" {}
variable "event_schedule_cron" {}
variable "log_retention" {}
variable "lambda_timeout" {}
variable "allowed_account_ids" {}
